// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAch6msSZcoAiPZWZsgLgf8U5KfYFD97vo',
    appId: '1:883888865686:web:0a2dec7035c1850b239db7',
    messagingSenderId: '883888865686',
    projectId: 'propertykar-6fa26',
    authDomain: 'propertykar-6fa26.firebaseapp.com',
    storageBucket: 'propertykar-6fa26.appspot.com',
    measurementId: 'G-ZKNYPSNK7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-XS0q8SjJ2b6mC8BE4tawlfrdBYyBj8Q',
    appId: '1:883888865686:android:0a76b1196dba242e239db7',
    messagingSenderId: '883888865686',
    projectId: 'propertykar-6fa26',
    storageBucket: 'propertykar-6fa26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX__wY3UtwE06vFXHWB22dc9yjqNPE6uE',
    appId: '1:883888865686:ios:090f7fbd5772913c239db7',
    messagingSenderId: '883888865686',
    projectId: 'propertykar-6fa26',
    storageBucket: 'propertykar-6fa26.appspot.com',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX__wY3UtwE06vFXHWB22dc9yjqNPE6uE',
    appId: '1:883888865686:ios:090f7fbd5772913c239db7',
    messagingSenderId: '883888865686',
    projectId: 'propertykar-6fa26',
    storageBucket: 'propertykar-6fa26.appspot.com',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAch6msSZcoAiPZWZsgLgf8U5KfYFD97vo',
    appId: '1:883888865686:web:182528905c66af5a239db7',
    messagingSenderId: '883888865686',
    projectId: 'propertykar-6fa26',
    authDomain: 'propertykar-6fa26.firebaseapp.com',
    storageBucket: 'propertykar-6fa26.appspot.com',
    measurementId: 'G-VTNWX698JC',
  );
}
